window.esdocSearchIndex = [
  [
    "@cedx/reverse-proxy/lib/application.js~application",
    "class/lib/application.js~Application.html",
    "<span>Application</span> <span class=\"search-result-import-path\">@cedx/reverse-proxy/lib/application.js</span>",
    "class"
  ],
  [
    "@cedx/reverse-proxy/lib/server.js~server",
    "class/lib/server.js~Server.html",
    "<span>Server</span> <span class=\"search-result-import-path\">@cedx/reverse-proxy/lib/server.js</span>",
    "class"
  ],
  [
    "application lib/application.js~application,application",
    "test-file/test/application_test.js.html#lineNumber9",
    "Application",
    "test"
  ],
  [
    "application#_parseconfig application#_parseconfig,application#_parseconfig",
    "test-file/test/application_test.js.html#lineNumber73",
    "Application #_parseConfig()",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber95",
    "Application #_parseConfig() should completes with an array if the parsed JSON configuration is valid",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber103",
    "Application #_parseConfig() should completes with an array if the parsed YAML configuration is valid",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber111",
    "Application #_parseConfig() should handle the loading of certificate files",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber74",
    "Application #_parseConfig() should throw an error if the configuration has an invalid format",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber81",
    "Application #_parseConfig() should throw an error if the parsed JSON configuration has no `routes` and no `target` properties",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber88",
    "Application #_parseConfig() should throw an error if the parsed YAML configuration has no `routes` and no `target` properties",
    "test"
  ],
  [
    "application#debug lib/application.js~application#debug,application#debug",
    "test-file/test/application_test.js.html#lineNumber14",
    "Application #debug",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber15",
    "Application #debug should be `false` in production environment",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber20",
    "Application #debug should be `true` in development environment",
    "test"
  ],
  [
    "application#env lib/application.js~application#env,application#env",
    "test-file/test/application_test.js.html#lineNumber29",
    "Application #env",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber30",
    "Application #env should be \"development\" if the NODE_ENV environment variable is not set",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber35",
    "Application #env should equal the value of `NODE_ENV` environment variable when it is set",
    "test"
  ],
  [
    "application#init lib/application.js~application#init,application#init",
    "test-file/test/application_test.js.html#lineNumber44",
    "Application #init()",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber53",
    "Application #init() should initialize the `servers` property from the JSON configuration",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber61",
    "Application #init() should initialize the `servers` property from the YAML configuration",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber45",
    "Application #init() should initialize the `servers` property from the command line arguments",
    "test"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "server lib/server.js~server,server",
    "test-file/test/server_test.js.html#lineNumber11",
    "Server",
    "test"
  ],
  [
    "server#_gethostname server#_gethostname,server#_gethostname",
    "test-file/test/server_test.js.html#lineNumber123",
    "Server #_getHostname()",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber124",
    "Server #_getHostname() it should return \"*\" if there is no \"Host\" header in the request",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber128",
    "Server #_getHostname() it should return the \"Host\" header found in the request, without the port number",
    "test"
  ],
  [
    "server#_normalizeroute server#_normalizeroute,server#_normalizeroute",
    "test-file/test/server_test.js.html#lineNumber136",
    "Server #_normalizeRoute()",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber137",
    "Server #_normalizeRoute() it should normalize a port on the local host",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber142",
    "Server #_normalizeRoute() it should normalize an authority",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber147",
    "Server #_normalizeRoute() it should normalize an origin",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber152",
    "Server #_normalizeRoute() it should normalize the HTTP headers",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber158",
    "Server #_normalizeRoute() it should throw an error if the route has an invalid format",
    "test"
  ],
  [
    "server#_sendstatus server#_sendstatus,server#_sendstatus",
    "test-file/test/server_test.js.html#lineNumber166",
    "Server #_sendStatus()",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber185",
    "Server #_sendStatus() it should set the response body",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber178",
    "Server #_sendStatus() it should set the response status",
    "test"
  ],
  [
    "server#address lib/server.js~server#address,server#address",
    "test-file/test/server_test.js.html#lineNumber16",
    "Server #address",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber17",
    "Server #address should have an \"any IPv4\" address as the default address",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber21",
    "Server #address should have the same host as the specified one",
    "test"
  ],
  [
    "server#listening lib/server.js~server#listening,server#listening",
    "test-file/test/server_test.js.html#lineNumber29",
    "Server #listening",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber30",
    "Server #listening should return whether the server is listening",
    "test"
  ],
  [
    "server#onclose lib/server.js~server#onclose,server#onclose",
    "test-file/test/server_test.js.html#lineNumber45",
    "Server #onClose",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber46",
    "Server #onClose should return an `Observable` instead of the underlying `Subject`",
    "test"
  ],
  [
    "server#onerror lib/server.js~server#onerror,server#onerror",
    "test-file/test/server_test.js.html#lineNumber56",
    "Server #onError",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber57",
    "Server #onError should return an `Observable` instead of the underlying `Subject`",
    "test"
  ],
  [
    "server#onlistening lib/server.js~server#onlistening,server#onlistening",
    "test-file/test/server_test.js.html#lineNumber67",
    "Server #onListening",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber68",
    "Server #onListening should return an `Observable` instead of the underlying `Subject`",
    "test"
  ],
  [
    "server#onrequest lib/server.js~server#onrequest,server#onrequest",
    "test-file/test/server_test.js.html#lineNumber78",
    "Server #onRequest",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber79",
    "Server #onRequest should return an `Observable` instead of the underlying `Subject`",
    "test"
  ],
  [
    "server#port lib/server.js~server#port,server#port",
    "test-file/test/server_test.js.html#lineNumber89",
    "Server #port",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber90",
    "Server #port should have 3000 as the default port",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber94",
    "Server #port should have the same port as the specified one",
    "test"
  ],
  [
    "server#routes lib/server.js~server#routes,server#routes",
    "test-file/test/server_test.js.html#lineNumber102",
    "Server #routes",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber103",
    "Server #routes should be empty by default",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber107",
    "Server #routes should create a default route if a target is specified",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber113",
    "Server #routes should normalize the specified targets",
    "test"
  ],
  [
    "lib/application.js",
    "file/lib/application.js.html",
    "lib/application.js",
    "file"
  ],
  [
    "lib/application.js~application#constructor",
    "class/lib/application.js~Application.html#instance-constructor-constructor",
    "lib/application.js~Application#constructor",
    "method"
  ],
  [
    "lib/application.js~application#debug",
    "class/lib/application.js~Application.html#instance-get-debug",
    "lib/application.js~Application#debug",
    "member"
  ],
  [
    "lib/application.js~application#env",
    "class/lib/application.js~Application.html#instance-get-env",
    "lib/application.js~Application#env",
    "member"
  ],
  [
    "lib/application.js~application#init",
    "class/lib/application.js~Application.html#instance-method-init",
    "lib/application.js~Application#init",
    "method"
  ],
  [
    "lib/application.js~application#run",
    "class/lib/application.js~Application.html#instance-method-run",
    "lib/application.js~Application#run",
    "method"
  ],
  [
    "lib/application.js~application#servers",
    "class/lib/application.js~Application.html#instance-member-servers",
    "lib/application.js~Application#servers",
    "member"
  ],
  [
    "lib/application.js~application.log_format",
    "class/lib/application.js~Application.html#static-get-LOG_FORMAT",
    "lib/application.js~Application.LOG_FORMAT",
    "member"
  ],
  [
    "lib/server.js",
    "file/lib/server.js.html",
    "lib/server.js",
    "file"
  ],
  [
    "lib/server.js~server#address",
    "class/lib/server.js~Server.html#instance-get-address",
    "lib/server.js~Server#address",
    "member"
  ],
  [
    "lib/server.js~server#close",
    "class/lib/server.js~Server.html#instance-method-close",
    "lib/server.js~Server#close",
    "method"
  ],
  [
    "lib/server.js~server#constructor",
    "class/lib/server.js~Server.html#instance-constructor-constructor",
    "lib/server.js~Server#constructor",
    "method"
  ],
  [
    "lib/server.js~server#listen",
    "class/lib/server.js~Server.html#instance-method-listen",
    "lib/server.js~Server#listen",
    "method"
  ],
  [
    "lib/server.js~server#listening",
    "class/lib/server.js~Server.html#instance-get-listening",
    "lib/server.js~Server#listening",
    "member"
  ],
  [
    "lib/server.js~server#onclose",
    "class/lib/server.js~Server.html#instance-get-onClose",
    "lib/server.js~Server#onClose",
    "member"
  ],
  [
    "lib/server.js~server#onerror",
    "class/lib/server.js~Server.html#instance-get-onError",
    "lib/server.js~Server#onError",
    "member"
  ],
  [
    "lib/server.js~server#onlistening",
    "class/lib/server.js~Server.html#instance-get-onListening",
    "lib/server.js~Server#onListening",
    "member"
  ],
  [
    "lib/server.js~server#onrequest",
    "class/lib/server.js~Server.html#instance-get-onRequest",
    "lib/server.js~Server#onRequest",
    "member"
  ],
  [
    "lib/server.js~server#port",
    "class/lib/server.js~Server.html#instance-get-port",
    "lib/server.js~Server#port",
    "member"
  ],
  [
    "lib/server.js~server#routes",
    "class/lib/server.js~Server.html#instance-member-routes",
    "lib/server.js~Server#routes",
    "member"
  ],
  [
    "lib/server.js~server.default_address",
    "class/lib/server.js~Server.html#static-get-DEFAULT_ADDRESS",
    "lib/server.js~Server.DEFAULT_ADDRESS",
    "member"
  ],
  [
    "lib/server.js~server.default_port",
    "class/lib/server.js~Server.html#static-get-DEFAULT_PORT",
    "lib/server.js~Server.DEFAULT_PORT",
    "member"
  ],
  [
    "test/application_test.js",
    "test-file/test/application_test.js.html",
    "test/application_test.js",
    "testFile"
  ],
  [
    "test/server_test.js",
    "test-file/test/server_test.js.html",
    "test/server_test.js",
    "testFile"
  ]
]