window.esdocSearchIndex = [
  [
    "@cedx/reverse-proxy/lib/application.js~application",
    "class/lib/application.js~Application.html",
    "<span>Application</span> <span class=\"search-result-import-path\">@cedx/reverse-proxy/lib/application.js</span>",
    "class"
  ],
  [
    "@cedx/reverse-proxy/lib/server.js~eventemitter",
    "variable/index.html#static-variable-EventEmitter",
    "<span>EventEmitter</span> <span class=\"search-result-import-path\">@cedx/reverse-proxy/lib/server.js</span>",
    "variable"
  ],
  [
    "@cedx/reverse-proxy/lib/server.js~server",
    "class/lib/server.js~Server.html",
    "<span>Server</span> <span class=\"search-result-import-path\">@cedx/reverse-proxy/lib/server.js</span>",
    "class"
  ],
  [
    "application lib/application.js~application,application",
    "test-file/test/application_test.js.html#lineNumber9",
    "Application",
    "test"
  ],
  [
    "application#_parseconfig application#_parseconfig,application#_parseconfig",
    "test-file/test/application_test.js.html#lineNumber70",
    "Application #_parseConfig()",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber104",
    "Application #_parseConfig() should completes with an array if the parsed JSON configuration is valid",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber111",
    "Application #_parseConfig() should completes with an array if the parsed YAML configuration is valid",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber118",
    "Application #_parseConfig() should handle the loading of certificate files",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber71",
    "Application #_parseConfig() should throw an error if the configuration has an invalid format",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber82",
    "Application #_parseConfig() should throw an error if the parsed JSON configuration has no `routes` and no `target` properties",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber93",
    "Application #_parseConfig() should throw an error if the parsed YAML configuration has no `routes` and no `target` properties",
    "test"
  ],
  [
    "application#debug lib/application.js~application#debug,application#debug",
    "test-file/test/application_test.js.html#lineNumber14",
    "Application #debug",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber15",
    "Application #debug should be `false` in production environment",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber20",
    "Application #debug should be `true` in development environment",
    "test"
  ],
  [
    "application#env lib/application.js~application#env,application#env",
    "test-file/test/application_test.js.html#lineNumber29",
    "Application #env",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber30",
    "Application #env should be \"development\" if the NODE_ENV environment variable is not set",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber35",
    "Application #env should equal the value of `NODE_ENV` environment variable when it is set",
    "test"
  ],
  [
    "application#init lib/application.js~application#init,application#init",
    "test-file/test/application_test.js.html#lineNumber44",
    "Application #init()",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber52",
    "Application #init() should initialize the `servers` property from the JSON configuration",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber59",
    "Application #init() should initialize the `servers` property from the YAML configuration",
    "test"
  ],
  [
    "",
    "test-file/test/application_test.js.html#lineNumber45",
    "Application #init() should initialize the `servers` property from the command line arguments",
    "test"
  ],
  [
    "server lib/server.js~server,server",
    "test-file/test/server_test.js.html#lineNumber10",
    "Server",
    "test"
  ],
  [
    "server#_gethostname server#_gethostname,server#_gethostname",
    "test-file/test/server_test.js.html#lineNumber78",
    "Server #_getHostname()",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber79",
    "Server #_getHostname() it should return \"*\" if there is no \"Host\" header in the request",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber83",
    "Server #_getHostname() it should return the \"Host\" header found in the request, without the port number",
    "test"
  ],
  [
    "server#_normalizeroute server#_normalizeroute,server#_normalizeroute",
    "test-file/test/server_test.js.html#lineNumber91",
    "Server #_normalizeRoute()",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber92",
    "Server #_normalizeRoute() it should normalize a port on the local host",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber97",
    "Server #_normalizeRoute() it should normalize an authority",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber102",
    "Server #_normalizeRoute() it should normalize an origin",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber107",
    "Server #_normalizeRoute() it should normalize the HTTP headers",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber113",
    "Server #_normalizeRoute() it should throw an error if the route has an invalid format",
    "test"
  ],
  [
    "server#_sendstatus server#_sendstatus,server#_sendstatus",
    "test-file/test/server_test.js.html#lineNumber121",
    "Server #_sendStatus()",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber140",
    "Server #_sendStatus() it should set the response body",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber133",
    "Server #_sendStatus() it should set the response status",
    "test"
  ],
  [
    "server#address lib/server.js~server#address,server#address",
    "test-file/test/server_test.js.html#lineNumber15",
    "Server #address",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber16",
    "Server #address should have an \"any IPv4\" address as the default address",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber20",
    "Server #address should have the same host as the specified one",
    "test"
  ],
  [
    "server#listening lib/server.js~server#listening,server#listening",
    "test-file/test/server_test.js.html#lineNumber28",
    "Server #listening",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber29",
    "Server #listening should return whether the server is listening",
    "test"
  ],
  [
    "server#port lib/server.js~server#port,server#port",
    "test-file/test/server_test.js.html#lineNumber44",
    "Server #port",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber45",
    "Server #port should have 3000 as the default port",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber49",
    "Server #port should have the same port as the specified one",
    "test"
  ],
  [
    "server#routes lib/server.js~server#routes,server#routes",
    "test-file/test/server_test.js.html#lineNumber57",
    "Server #routes",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber58",
    "Server #routes should be empty by default",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber62",
    "Server #routes should create a default route if a target is specified",
    "test"
  ],
  [
    "",
    "test-file/test/server_test.js.html#lineNumber68",
    "Server #routes should normalize the specified targets",
    "test"
  ],
  [
    "lib/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "lib/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "lib/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "lib/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "lib/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "lib/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "lib/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "lib/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "lib/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "lib/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "lib/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "lib/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "lib/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "lib/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "lib/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "lib/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "lib/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "lib/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "lib/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "lib/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "lib/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "lib/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "lib/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "lib/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "lib/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "lib/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~String",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "lib/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "lib/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "lib/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "lib/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "lib/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "lib/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "lib/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "lib/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "lib/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "lib/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "lib/.external-ecmascript.js~null",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~string",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "lib/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "lib/application.js",
    "file/lib/application.js.html",
    "lib/application.js",
    "file"
  ],
  [
    "lib/application.js~application#[symbol.tostringtag]",
    "class/lib/application.js~Application.html#instance-get-[Symbol.toStringTag]",
    "lib/application.js~Application#[Symbol.toStringTag]",
    "member"
  ],
  [
    "lib/application.js~application#constructor",
    "class/lib/application.js~Application.html#instance-constructor-constructor",
    "lib/application.js~Application#constructor",
    "method"
  ],
  [
    "lib/application.js~application#debug",
    "class/lib/application.js~Application.html#instance-get-debug",
    "lib/application.js~Application#debug",
    "member"
  ],
  [
    "lib/application.js~application#env",
    "class/lib/application.js~Application.html#instance-get-env",
    "lib/application.js~Application#env",
    "member"
  ],
  [
    "lib/application.js~application#init",
    "class/lib/application.js~Application.html#instance-method-init",
    "lib/application.js~Application#init",
    "method"
  ],
  [
    "lib/application.js~application#run",
    "class/lib/application.js~Application.html#instance-method-run",
    "lib/application.js~Application#run",
    "method"
  ],
  [
    "lib/application.js~application#servers",
    "class/lib/application.js~Application.html#instance-member-servers",
    "lib/application.js~Application#servers",
    "member"
  ],
  [
    "lib/application.js~application.log_format",
    "class/lib/application.js~Application.html#static-get-LOG_FORMAT",
    "lib/application.js~Application.LOG_FORMAT",
    "member"
  ],
  [
    "lib/server.js",
    "file/lib/server.js.html",
    "lib/server.js",
    "file"
  ],
  [
    "lib/server.js~server#[symbol.tostringtag]",
    "class/lib/server.js~Server.html#instance-get-[Symbol.toStringTag]",
    "lib/server.js~Server#[Symbol.toStringTag]",
    "member"
  ],
  [
    "lib/server.js~server#address",
    "class/lib/server.js~Server.html#instance-get-address",
    "lib/server.js~Server#address",
    "member"
  ],
  [
    "lib/server.js~server#close",
    "class/lib/server.js~Server.html#instance-method-close",
    "lib/server.js~Server#close",
    "method"
  ],
  [
    "lib/server.js~server#constructor",
    "class/lib/server.js~Server.html#instance-constructor-constructor",
    "lib/server.js~Server#constructor",
    "method"
  ],
  [
    "lib/server.js~server#listen",
    "class/lib/server.js~Server.html#instance-method-listen",
    "lib/server.js~Server#listen",
    "method"
  ],
  [
    "lib/server.js~server#listening",
    "class/lib/server.js~Server.html#instance-get-listening",
    "lib/server.js~Server#listening",
    "member"
  ],
  [
    "lib/server.js~server#port",
    "class/lib/server.js~Server.html#instance-get-port",
    "lib/server.js~Server#port",
    "member"
  ],
  [
    "lib/server.js~server#routes",
    "class/lib/server.js~Server.html#instance-member-routes",
    "lib/server.js~Server#routes",
    "member"
  ],
  [
    "lib/server.js~server.default_address",
    "class/lib/server.js~Server.html#static-get-DEFAULT_ADDRESS",
    "lib/server.js~Server.DEFAULT_ADDRESS",
    "member"
  ],
  [
    "lib/server.js~server.default_port",
    "class/lib/server.js~Server.html#static-get-DEFAULT_PORT",
    "lib/server.js~Server.DEFAULT_PORT",
    "member"
  ],
  [
    "test/application_test.js",
    "test-file/test/application_test.js.html",
    "test/application_test.js",
    "testFile"
  ],
  [
    "test/server_test.js",
    "test-file/test/server_test.js.html",
    "test/server_test.js",
    "testFile"
  ]
]